config/routes.rb
Rails.application.routes.draw do
  resources :rooms

  root 'welcome#index'

  resources :users

  get  "users/index"
  get  "/login"           => "users#login"
  post "/signin"          => "users#authenticate"
  get  "/signup"          => "users#new"
  get  "/logout"          => "users#logout"
  get  "/password"        => "users#password"
  post "/password_update" => "users#password_update"
  get  "/remember_password/:id" => "users#remember_password_index", :as => "remember"
  post "/remember_password"     => "users#remember_password"

  get "/schedule_room" => 'schedulings#schedule_room', as: 'schedule_room'
end

app/models/room.rb
class Room < ActiveRecord::Base
  validates_presence_of :description
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:description)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "erro") %> proibiu essa sala de ser salva:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Edição de sala</h1>

<%= render 'form' %>

<%= link_to 'Voltar', rooms_path %>

app/views/rooms/index.html.erb
<h1>Salas Cadastradas</h1>

<div class="modulo">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Descrição</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.description %></td>
          <td><%= link_to 'Agenda', room %></td>
          <td><%= link_to 'Editar', edit_room_path(room) %></td>
          <td><%= link_to 'Remover', room, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/new.html.erb
<h1>Nova sala</h1>

<%= render 'form' %>

<%= link_to 'Voltar', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome da Sala:</strong>
  <%= @room.description %>
</p>

<br>
<br>
<p>Agenda da sala</p>
<table class="table table-striped">
  <tr>
    <th>Horário</td>
    <th><%= days_of_week[0] %></th>
    <th><%= days_of_week[1] %></th>
    <th><%= days_of_week[2] %></th>
    <th><%= days_of_week[3] %></th>
    <th><%= days_of_week[4] %></th>
    <th><%= days_of_week[5] %></th>
    <th><%= days_of_week[6] %></th>
  </tr>

  <% Constants::HOURS.each do |hour| %>
    <tr data-hour="<%= hour %>">
      <td class="col-md-1"><%= hour %></td>
      <% days_of_week.each do |day| %>
        <% scheduling = check_scheduling(@room, day, hour) %>

        <% if can_schedule?(scheduling) %>
          <td class="col-md-1" data-day="<%= day %>">
            <%= link_to scheduling_description(scheduling),
                        schedule_room_path(room_id: @room.id, date: day, time: hour),
                        data: {confirm: 'tem certeza que deseja reservar/cancelar?'}, remote: true %>
          </td>
        <% else %>
          <td class="col-md-1"><%= scheduling_description(scheduling) %></td>
        <% end %>
      <% end %>
    </tr>
  <% end %>
</table>