config/routes.rb
Rails.application.routes.draw do
  resources :rooms

  root 'welcome#index'

  resources :users

  get  "users/index"
  get  "/login"           => "users#login"
  post "/signin"          => "users#authenticate"
  get  "/signup"          => "users#new"
  get  "/logout"          => "users#logout"
  get  "/password"        => "users#password"
  post "/password_update" => "users#password_update"
  get  "/remember_password/:id" => "users#remember_password_index", :as => "remember"
  post "/remember_password"     => "users#remember_password"

  get "/schedule_room" => 'schedulings#schedule_room', as: 'schedule_room'
end

app/models/scheduling.rb
class Scheduling < ActiveRecord::Base
  validates_presence_of :room_id
  validates_presence_of :time

  belongs_to :user

  def self.handle_scheduling(room_id, date, current_user)
    scheduling = Scheduling.find_by(room_id: room_id, time: date)

    if scheduling.try(:user_id) == current_user.id
      scheduling.destroy
    elsif scheduling.blank?
      scheduling = current_user.schedulings.create(room_id: room_id, time: date)
    end
  end
end

app/controllers/schedulings_controller.rb
class SchedulingsController < ApplicationController
  before_action :set_scheduling, only: [:update, :destroy]

  def schedule_room
    @scheduling = Scheduling.handle_scheduling(params[:room_id], get_date_time(params[:date].to_date, params[:time]), current_user)
  end

  private
  def set_scheduling
    @scheduling = Scheduling.find(params[:id])
  end

  def scheduling_params
    params.require(:scheduling).permit(:room_id, :user_id, :time)
  end

  def get_date_time(date, time)
    DateTime.new(date.year, date.month, date.day, time.to_i)
  end
end

app/helpers/schedulings_helper.rb
module SchedulingsHelper
end

app/views/schedulings/schedule_room.js.erb
<% if @scheduling.user_id == @current_user.id %>
  <%
  hour   = l(@scheduling.time, format: :hour)
  day    = l(@scheduling.time, format: :date)
  text   = @scheduling.persisted? ? "Reservado para #{@scheduling.user.name}" : 'Disponível'
  action = @scheduling.persisted? ? 'cancelar' : 'reservar'
  %>
  $('table tr[data-hour="<%= hour %>"]').find('td[data-day="<%= day %>"]').
    html('<%= j link_to(text, schedule_room_path(room_id: @scheduling.room_id, date: day, time: hour),
                        data: {confirm: "tem certeza que deseja #{action}?"}, remote: true) %>');
<% else %>
  alert('Reservado para outro usuário')
<% end %>