config/routes.rb
Rails.application.routes.draw do
  resources :rooms

  root 'welcome#index'

  resources :users

  get  "users/index"
  get  "/login"           => "users#login"
  post "/signin"          => "users#authenticate"
  get  "/signup"          => "users#new"
  get  "/logout"          => "users#logout"
  get  "/password"        => "users#password"
  post "/password_update" => "users#password_update"
  get  "/remember_password/:id" => "users#remember_password_index", :as => "remember"
  post "/remember_password"     => "users#remember_password"

  get "/schedule_room" => 'schedulings#schedule_room', as: 'schedule_room'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BioRitmoScheduling</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag "favicon.ico" %>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">x</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Bioritmo</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Salas de Reunião <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% Room.order(:description).each do |room| %>
                  <li><%= link_to room.description, room_path(room) %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to "Nova sala de reunião", new_room_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Ver todas", rooms_path %></li>
              </ul>
            </li>
            <% if @current_user and @current_user.admin? %>
              <li class="active"><a href="/users">Usuários </a></li>
            <% end %>
          </ul>
          <% if session[:user_id] %>
          <ul class="nav navbar-nav navbar-right">
            <a class="navbar-text" href=<%= "/users/#{@current_user.id}/edit"%>> <%= @current_user.name %> | <%= @current_user.email %></a>
            <li><%= link_to "Logout", logout_path %></li>
          </ul>
        <% end %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>